services:
  backend:
    build: ./product/backend
    ports: 
      - "8080:8080"
  frontend:
    build: ./product/frontendNext
    ports:
      - "8050:8050"
    depends_on:
      - backend
  ml:
    build: ./product/ml
    ports:
      - "8000:8000"
    depends_on:
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  postgres_data: