services:
  server:
    image: yosesotomayor/retocasas_v2-server:v0.0.4
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  app:
    image: yosesotomayor/retocasas_v2-app:v0.0.8
    ports: ["3000:3000"]
    environment:
      - NEXT_TELEMETRY_DISABLED=1

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge