services:
  server:
    image: zamcv/house-server:v0.0.8
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - app-network

  app:
    image: zamcv/house-app:v0.0.9
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network

  db:
    image: postgres:15
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge