services:
  server-backend:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
    - ./server:/app/server
    - ./utils:/app/utils:ro
    - ./data:/app/data:ro
    restart: unless-stopped

  # client-frontend:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./app:/app
  #   restart: unless-stopped