version: "3.9"

services:
  ml-backend:
    build:
      context: ./ML
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ML:/app/ML
    restart: unless-stopped