services:
  ml-backend:
    build:
      context: ./ML
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # URIs de MLflow (tracking y registry en DagsHub)
      MLFLOW_TRACKING_URI: "https://dagshub.com/yosesotomayor/retoCasas_v2.mlflow"
      MLFLOW_REGISTRY_URI: "https://dagshub.com/yosesotomayor/retoCasas_v2.mlflow"

      # Modelo a cargar
      MODEL_NAME: "elnet_lgbm"
      MODEL_ALIAS: "champion"

      # Puerto de tu app Flask (tu código ya lo usa)
      PORT: "8000"

      # MLflow
      MLFLOW_TRACKING_USERNAME: "yosesotomayor"
      MLFLOW_TRACKING_TOKEN: "${DAGSHUB_TOKEN}"
      MLFLOW_TRACKING_PASSWORD: "${DAGSHUB_TOKEN}"
    volumes:
      - ./ML:/app/ML
    restart: unless-stopped