services:
  server:
    image: yosesotomayor/retocasas_v2-server:v0.0.1
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
    - ./server:/app/server
    - ./utils:/app/utils:ro
    - ./data:/app/data:ro
    restart: unless-stopped
  app:
    image: yosesotomayor/retocasas_v2-app:v0.0.1
    ports: ["3000:3000"]
    environment:
      - NEXT_TELEMETRY_DISABLED=1